input {
  rabbitmq {
    host        => "127.0.0.1"
    port        => 5672
    user        => ""
    password    => ""
    vhost       => "/vhost"
    queue       => "TXN"        # your dedicated log queue
    durable     => true
    auto_delete => false
    codec       => "json"             # if your messages are JSON
  }
}

filter {
  # if message field is a JSON string, parse it
  json {
    source => "message"
  }

  # add extra fields if needed
  mutate {
    add_field => { "environment" => "production" }
  }

  # parse timestamp from your message if exists
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
}