version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    # restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data   # Persistent data
      - ./init-scripts:/docker-entrypoint-initdb.d    # Create user_management schema
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_replication_slots=10", "-c", "max_wal_senders=10"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "terasadmin"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
#     networks:
#       - ocr-network-api

# networks:
#   ocr-network-api:
#     external: true